#ifndef STATICDATA_H
#define STATICDATA_H

#include <QGraphicsRectItem>

const qint32 WINDOW_WIDTH = 1280;
const qint32 WINDOW_HEIGHT = 720;

const qint32 MAIN_MENU_BUTTON_WIDTH = 150;
const qint32 MAIN_MENU_BUTTON_HEIGHT = 75;

const qint32 CANCEL_EXIT_BUTTON_WIDTH = 75;
const qint32 CANCEL_EXIT_BUTTON_HEIGHT = 75;

const qint32 SPEED_SLIDER_RECT_WIDTH = 150;
const qint32 SPEED_SLIDER_RECT_HEIGHT = 75;

const qint32 SPEED_SLIDER_WIDTH = 130;
const qint32 SPEED_SLIDER_HEIGHT = 35;

const qint32 LIFETIME_SLIDER_RECT_WIDTH = 150;
const qint32 LIFETIME_SLIDER_RECT_HEIGHT = 75;

const qint32 LIFETIME_SLIDER_WIDTH = 130;
const qint32 LIFETIME_SLIDER_HEIGHT = 35;

const qint32 NUMBER_OF_SALUTES_LABEL_WIDTH = 200;
const qint32 NUMBER_OF_SALUTES_LABEL_HEIGHT = 35;

const qint32 PARTICLE_SIZE = 10;


#endif // STATICDATA_H
